Вот пример декоратора на Python, который будет перехватывать ошибки и повторять функцию максимум N раз:

```python
import functools


def retry(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        max_retries = 3
        for i in range(max_retries):
            try:
                result = func(*args, **kwargs)
                return result
            except Exception as e:
                print(f'Error occurred: {e}. Retrying ({i + 1}/{max_retries})...')
        raise Exception(f'Function {func.__name__} failed after {max_retries} attempts.')

    return wrapper

```

Для использования декоратора вам нужно добавить @retry перед определением функции, которую вы хотите обернуть:

```python
@retry
def my_function(arg1, arg2):
# ваш код здесь

```

В этом примере функция my_function будет повторно вызываться до трех раз в случае ошибки, до тех пор, пока она не
выполнится успешно. Если после трех попыток функция не выполнится успешно, вы получите исключение.

Вы можете настроить параметр max_retries, чтобы изменить количество попыток или добавить его как аргумент декоратора,
чтобы делать эти настройки динамически.

<div align="right">

[Вернуться к вопросам](../Вопросы.md)

</div>
