Это возможно из-за того, что Python имеет функцию под названием "name mangling", которая изменяет имена атрибутов
класса или методов путем добавления двойного подчеркивания "__" в начале их имен. Это сделано для того, чтобы
предотвратить случайное переименование атрибутов в подклассах, которые будут унаследованы суперклассом.

В этом примере, "__mangled" является приватным и скрытым атрибутом, и он был переименован в "_MangledGlobal__mangled"
во время исполнения. Это означает, что вы можете обращаться к атрибуту с исходным именем "__mangled" только внутри
определения класса. Если вы попытаетесь обратиться к атрибуту с исходным именем "__mangled" извне класса, вы получите
ошибку "AttributeError" потому что атрибут фактически был переименован.

В нашем коде, метод "test" возвращает значение приватного атрибута "__mangled", но мы успешно можем обратиться к этому
значению снова, используя измененное имя атрибута "_MangledGlobal__mangled". Поэтому у нас нет ошибки и утверждение
"assert" успешно проходит.

<div align="right">

[Вернуться к вопросам](../Вопросы.md)

</div>
